const enums = Object.freeze({
  KeyBoardsButtons: {
    Registration: "Регистрација",
    AboutUs: "За нас",
    MakeAnAppointment: "Закажи преглед",
    ContactUs: "Контакт и локација",
    MainMenu: "Главно мени",
    Doctors: "Доктори",
    FZO: "Онлајн консултација",
    InviteFriend: "Препорачај пријател",
    News: "Новости",
    AskUsQuestion: "Разговарај со нас",
    Pricing: "Ценовник",
    AboutUsBack: "Назад",
    MyProfile: "Мои податоци",
    OnLineShop: "Онлајн плаќање",
  },
  KeyBoardButtonsValues: {
    Registration: "RegistrationMainMenuButton",
    AboutUs: "AboutUsMainMenuButton",
    MakeAnAppointment: "https://sistinaoftalmologija.mk/viber-chat",
    ContactUs: "ContactUsMainMenuButton",
    MainMenu: "MainMenuButton",
    Doctors: "https://sistinaoftalmologija.mk/doktori/",
    FZO: "https://sistinaoftalmologija.mk/onlineuslugi/",
    InviteFriend: "",
    News: "https://sistinaoftalmologija.mk/novosti-i-promocii/",
    AskUsQuestion: "ContactUsAskQuestion",
    Pricing: "https://sistinaoftalmologija.mk/onlineuslugi/cenovnik-online/",
    AboutUsBack: "Назад",
    MyProfile: "MyProfileMainMenuButton",
    PointsStatus: "MyPointsStatusButton",
    EditMyProfile: "EditMyProfileButton",
    EditYes: "EditProfileYesButton",
    EditNo: "EditProfileNoButton",
    ReferFriendButton: "ReferFriendButton",
    OnLineShop : "https://sistinaoftalmologija.mk/onlineuslugi/cenovnik-online/"
  },
  KeyBoarsActionTypes: {
    OpenUrl: "open-url",
    Reply: "reply",
  },
  RegistrationNavigationButtons: {
    Texts: {
      Next: "Продолжи",
      Back: "Назад",
      HasID: "Да",
      NoId: "Не",
      Agree: "Се согласувам",
      Disagree: "Не се согласувам",
    },
    Values: {
      Next: "RegistrationNavigationButtonNext",
      Back: "RegistrationNavigationButtonBack",
      HasID: "RegistrationNavigationButtonHasID",
      NoId: "RegistrationNavigationButtonNoID",
      NoEmail: "RegistrationNavigationButtonNoEmail",
      HasEmail: "RegistrationNavigationButtonHasEmail",
      Agree: "RegistrationNavigationButtonAgreed",
      Disagre: "RegistrationNavigationButtonDisagree",
    },
  },
  KeyboardColors: {
    BackGroundColor: "#006BB6",
    FrontColor: "#FFFFFF",
  },
});

module.exports = enums;
